In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("D:/Projects/Movie Recommendation Project/notebook/DATA/movies_metadata_small.csv")

In [3]:
credits = pd.read_csv('D:/Projects/Movie Recommendation Project/notebook/DATA/credits_small.csv')

In [4]:
print(len(movies))
print(len(credits))

8833
8833

In [5]:
credits.head(1)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862

In [6]:
## Now we have two data sets so for easier to process we will merge the both the dataset on the basis of title.

movies = movies.merge(credits,on='id')

In [7]:
movies.head()

,genres,id,overview,popularity,release_date,tagline,title,vote_average,cast,crew
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995,NaN,Toy Story,7.7,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,When siblings Judy and Peter discover an encha...,17.015539,1995,Roll the dice and unleash the excitement!,Jumanji,6.9,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,A family wedding reignites the ancient feud be...,11.712900,1995,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Just when George Banks has recovered from his ...,8.387519,1995,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [8]:
movies.columns

Index(['genres', 'id', 'overview', 'popularity', 'release_date', 'tagline',
       'title', 'vote_average', 'cast', 'crew'],
      dtype='object')

## So here we are gonna to keep some selective columns.
### genres
### id
### overview
### title
### cast
### crew

In [10]:
movies = movies[['id','title','overview','genres','cast','crew']]

In [11]:
movies.head()

,id,title,overview,genres,cast,crew
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [12]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
cast        0
crew        0
dtype: int64

In [13]:
movies.duplicated().sum()

0

#### Now we will merge columns overviw,genres,cast and crew into Tags. By converting themm into a same data type.

In [14]:
movies.iloc[0].genres

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [15]:
import ast # this is use to convert strings into list

In [16]:
def transform(obj):
    lst = []
    for i in ast.literal_eval(obj):
        lst.append(i['name'])
    return lst

In [17]:
movies['genres'] = movies['genres'].apply(transform)

In [18]:
movies.head()

,id,title,overview,genres,cast,crew
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

#### Now we dont need all the cast members so we will take only first three cast members. for that we will create a function

In [19]:
def transform_1(obj):
    lst = []
    count = 0
    for i in ast.literal_eval(obj):
        if count != 3:
            lst.append(i['name'])
            count += 1
        else:
            break
    return lst

In [20]:
movies['cast'] = movies['cast'].apply(transform_1)

In [21]:
## we will create a function to fetch director from crew.

def fetch_director(obj):
    lst = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            lst.append(i['name'])
            break
    return lst

In [22]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [23]:
movies.head()

,id,title,overview,genres,cast,crew
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter]
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston]
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch]
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]","[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker]
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer]

In [24]:
## here overview column is in string format so we will convert it into list.append

movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [25]:
movies.head()

,id,title,overview,genres,cast,crew
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter]
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston]
2,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch]
3,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[Comedy, Drama, Romance]","[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker]
4,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...",[Comedy],"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer]

In [26]:
## here there are lots of spaces between names so we will have to remove that.

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [27]:
movies.head()

,id,title,overview,genres,cast,crew
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter]
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston]
2,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Romance, Comedy]","[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch]
3,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[Comedy, Drama, Romance]","[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker]
4,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...",[Comedy],"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer]

In [28]:
## Now we will concatenate overview, genres, cast and crew into Tags

movies['Tags'] = movies['overview'] + movies['genres'] + movies['cast'] + movies['crew']

In [29]:
movies.head()

,id,title,overview,genres,cast,crew,Tags
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[When, siblings, Judy, and, Peter, discover, a..."
2,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Romance, Comedy]","[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch],"[A, family, wedding, reignites, the, ancient, ..."
3,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[Comedy, Drama, Romance]","[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker],"[Cheated, on,, mistreated, and, stepped, on,, ..."
4,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...",[Comedy],"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer],"[Just, when, George, Banks, has, recovered, fr..."

In [30]:
new_dataframe = movies[['id','title','Tags']]

In [31]:
new_dataframe

,id,title,Tags
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a..."
2,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ..."
3,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ..."
4,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr..."
...,...,...,...
8828,7014,Themroc,"[Made, without, proper, language,, just, gibbe..."
8829,411516,A German Life,"[Brunhilde, Pomsel, describes, herself, as, an..."
8830,433410,Self-criticism of a Bourgeois Dog,"[A, bourgeois, dog, confesses, how, he, was, t..."
8831,28469,Der Herr Karl,"[No, overview, found., Comedy, HelmutQualtinger]"
8832,460135,LEGO DC Super Hero Girls: Brain Drain,"[When, Supergirl,, Wonder, Woman,, Batgirl,, B..."

In [32]:
new_dataframe['Tags'] = new_dataframe['Tags'].apply(lambda x:" ".join(x))

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9700\1805685201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe['Tags'] = new_dataframe['Tags'].apply(lambda x:" ".join(x))

In [33]:
new_dataframe['Tags'] = new_dataframe['Tags'].apply(lambda x:x.lower())

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9700\940343861.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe['Tags'] = new_dataframe['Tags'].apply(lambda x:x.lower())

In [34]:
new_dataframe.head()

,id,title,Tags
0,862,Toy Story,"led by woody, andy's toys live happily in his ..."
1,8844,Jumanji,when siblings judy and peter discover an encha...
2,15602,Grumpier Old Men,a family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,just when george banks has recovered from his ...

In [35]:
new_dataframe['Tags'][0]

"led by woody, andy's toys live happily in his room until andy's birthday brings buzz lightyear onto the scene. afraid of losing his place in andy's heart, woody plots against buzz. but when circumstances separate buzz and woody from their owner, the duo eventually learns to put aside their differences. animation comedy family tomhanks timallen donrickles johnlasseter"

#### now we will do text vectorization using bag of words.

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [37]:
vectors = cv.fit_transform(new_dataframe['Tags']).toarray()

In [38]:
## here most of the words have same origin so we will do stemming here.

import nltk

In [39]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [40]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [41]:
new_dataframe['Tags'] = new_dataframe['Tags'].apply(stem)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9700\680087494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe['Tags'] = new_dataframe['Tags'].apply(stem)

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
similarity = cosine_similarity(vectors)

In [44]:
## Now we will create a function for recommendation of movies.

def recommend_movies(movie):
    movie_index = new_dataframe[new_dataframe['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_dataframe.iloc[i[0]].title)

In [45]:
recommend_movies("Groundhog Day")

The Knot
Rare Birds
King of Hearts
Mumford
Snow days

In [46]:
import pickle

In [47]:
pickle.dump(new_dataframe,open('movies.pkl','wb'))

In [48]:
new_dataframe['title'].values

array(['Toy Story', 'Jumanji', 'Grumpier Old Men', ...,
       'Self-criticism of a Bourgeois Dog', 'Der Herr Karl',
       'LEGO DC Super Hero Girls: Brain Drain'], dtype=object)

In [49]:
pickle.dump(new_dataframe.to_dict(),open('movie_dict.pkl','wb'))

In [50]:
pickle.dump(similarity,open('similarity.pkl','wb'))